service: remotion
app: othman

useDotenv: true # Load environment variables from .env

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  environment:
    ELEVENLABS_API_KEY: ${env:ELEVENLABS_API_KEY}
    ASSEMBLYAI_API_KEY: ${env:ASSEMBLYAI_API_KEY}
    AWS_S3_ACCESS_KEY_ID: ${env:AWS_S3_ACCESS_KEY_ID}
    AWS_S3_SECRET_ACCESS_KEY: ${env:AWS_S3_SECRET_ACCESS_KEY}
    AWS_S3_REGION: ${env:AWS_S3_REGION}
    AWS_BUCKET_NAME: ${env:AWS_BUCKET_NAME}
    REMOTION_SERVE_URL: ${env:REMOTION_SERVE_URL}
    REMOTION_LAMBDA_FUNCTION_NAME: ${env:REMOTION_LAMBDA_FUNCTION_NAME}
    REMOTION_LAMBDA_REGION: ${env:REMOTION_LAMBDA_REGION}
    REMOTION_COMPOSITION_ID: ${env:REMOTION_COMPOSITION_ID}

functions:
  api: # this the function name
    handler: src/index.handler # Replace 'index' with your TypeScript file name
    events:
      - http:
          path: api
          method: post
          cors: true

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**
